### ISSUE TITLE
Bottom overflowed by 2.0 pixels

### ISSUE THREAD

**Issue by fallenwood** [loshine/flutter-nga#1]
Device: Xiaomi 4S, 5 Inches
OS:      MIUI 10, Android 7.0
Version: Latest master
![screenshot_2018-12-17-11-46-09-664_xyz loshine flutternga](https://user-images.githubusercontent.com/11188646/50065448-94ff0d80-01f1-11e9-8092-eea1e3fce71d.png)

**Comment by loshine** [comment]
已修复
